### ISSUE TITLE
colored throwing exception on Windows 11

### ISSUE THREAD

**Issue by raffareis** [Ailothaen/RedditArchiver-standalone#3]
The `colored` library used for coloring the console feedback, thows an exception on Windows 11:

```
[x] Uncaught problem: function 'SetsConsoleMode' not found
Traceback (most recent call last):
  File "RedditArchiver.py", line 392, in <module>
    myprint(f'[i] {len(submission_id_list)} submissions to download', 14)
  File "RedditArchiver.py", line 301, in myprint
    print(f"{colored.fg(color)}{message}{colored.attr(0)}")
             ^^^^^^^^^^^^^^^^^
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\colored\colored.py", line 276, in fg
    return Colored(name).foreground()
           ^^^^^^^^^^^^^
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\colored\colored.py", line 48, in __init__
    self.enable_windows_terminal_mode()
  File "AppData\Local\Programs\Python\Python311\Lib\site-packages\colored\colored.py", line 145, in enable_windows_terminal_mode
    ok = windll.kernel32.SetsConsoleMode(wintypes.HANDLE(hStdout), mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: function 'SetsConsoleMode' not found. Did you mean: 'GetConsoleMode'?
```

I fixed it by switching to the `colorama` lib, but have not tested it on other OS, and also my linter prettified the hell of the file so I didn't create a pull request. If anyone is interested on the fix, it consists on installing `colorama` and then these changes on RedditArchiver.py:

```python
from colorama import Fore, Style, init
init(autoreset=True)
```
Then substitute the `myprint` function as follows:
```python
def myprint(message, color, stderr=False):
    """
    Easy wrapper for print
    """
    color = color % 8
    color_dict = {
        0: Fore.BLACK,
        1: Fore.RED,
        2: Fore.GREEN,
        3: Fore.YELLOW,
        4: Fore.BLUE,
        5: Fore.MAGENTA,
        6: Fore.CYAN,
        7: Fore.WHITE
    }
    if stderr:
        print(
            f"{color_dict[color]}{message}{Style.RESET_ALL}", file=sys.stderr)
    else:
        if args.quiet:
            return None
        else:
            print(f"{color_dict[color]}{message}{Style.RESET_ALL}")
```

Result: 
![image](https://github.com/Ailothaen/RedditArchiver-standalone/assets/4365623/55485ea3-3230-4829-8863-d48a08de34df)

**Comment by Ailothaen** [comment]
Hello raffaeis,

I see that, recently, there was [an issue with colored](https://gitlab.com/dslackw/colored/-/issues/29) regarding this exact function, but the fix has not been pushed to PyPI yet.

Could you try to run `pip install colored==2.1.1` and tell me if the problem is still here?

**Comment by raffareis** [comment]
That solves it!

**Comment by Ailothaen** [comment]
Awesome 😊

I am going to change `requirements.txt` to prevent "erratic" versions to be installed.

Thank you for your report!
